import animate from "tailwindcss-animate";

const materialNamedColors = {
  "surface-container": "var(--theme-color-surface-container, #3366CC)",
  "inverse-on-surface": "var(--theme-color-inverse-on-surface, #3366CC)",
  "on-secondary": "var(--theme-color-on-secondary, #3366CC)",
  "on-background": "var(--theme-color-on-background, #3366CC)",
  surface: "var(--theme-color-surface, #3366CC)",
  "tertiary-fixed": "var(--theme-color-tertiary-fixed, #3366CC)",
  "inverse-primary": "var(--theme-color-inverse-primary, #3366CC)",
  "surface-bright": "var(--theme-color-surface-bright, #3366CC)",
  primary: "var(--theme-color-primary, #3366CC)",
  "secondary-container": "var(--theme-color-secondary-container, #3366CC)",
  "primary-fixed-dim": "var(--theme-color-primary-fixed-dim, #3366CC)",
  "primary-fixed": "var(--theme-color-primary-fixed, #3366CC)",
  "secondary-fixed": "var(--theme-color-secondary-fixed, #3366CC)",
  "surface-container-low": "var(--theme-color-surface-container-low, #3366CC)",
  "on-surface-variant": "var(--theme-color-on-surface-variant, #3366CC)",
  "tertiary-container": "var(--theme-color-tertiary-container, #3366CC)",
  "on-secondary-fixed": "var(--theme-color-on-secondary-fixed, #3366CC)",
  "on-secondary-container": "var(--theme-color-on-secondary-container, #3366CC)",
  "on-primary-container": "var(--theme-color-on-primary-container, #3366CC)",
  "on-error-container": "var(--theme-color-on-error-container, #3366CC)",
  outline: "var(--theme-color-outline, #3366CC)",
  "on-tertiary-fixed": "var(--theme-color-on-tertiary-fixed, #3366CC)",
  "outline-variant": "var(--theme-color-outline-variant, #3366CC)",
  "on-error": "var(--theme-color-on-error, #3366CC)",
  "on-primary-fixed": "var(--theme-color-on-primary-fixed, #3366CC)",
  background: "var(--theme-color-background, #3366CC)",
  "surface-variant": "var(--theme-color-surface-variant, #3366CC)",
  "surface-dim": "var(--theme-color-surface-dim, #3366CC)",
  "tertiary-fixed-dim": "var(--theme-color-tertiary-fixed-dim, #3366CC)",
  "on-primary-fixed-variant": "var(--theme-color-on-primary-fixed-variant, #3366CC)",
  "surface-tint": "var(--theme-color-surface-tint, #3366CC)",
  secondary: "var(--theme-color-secondary, #3366CC)",
  "on-tertiary": "var(--theme-color-on-tertiary, #3366CC)",
  "on-tertiary-container": "var(--theme-color-on-tertiary-container, #3366CC)",
  "surface-container-high": "var(--theme-color-surface-container-high, #3366CC)",
  tertiary: "var(--theme-color-tertiary, #3366CC)",
  "on-tertiary-fixed-variant": "var(--theme-color-on-tertiary-fixed-variant, #3366CC)",
  "on-surface": "var(--theme-color-on-surface, #3366CC)",
  "on-primary": "var(--theme-color-on-primary, #3366CC)",
  "error-container": "var(--theme-color-error-container, #3366CC)",
  "surface-container-lowest": "var(--theme-color-surface-container-lowest, #3366CC)",
  "on-secondary-fixed-variant": "var(--theme-color-on-secondary-fixed-variant, #3366CC)",
  "inverse-surface": "var(--theme-color-inverse-surface, #3366CC)",
  "surface-container-highest": "var(--theme-color-surface-container-highest, #3366CC)",
  "primary-container": "var(--theme-color-primary-container, #3366CC)",
  error: "var(--theme-color-error, #3366CC)",
  "secondary-fixed-dim": "var(--theme-color-secondary-fixed-dim, #3366CC)",
  neutral: "var(--theme-color-neutral, #3366CC)",
};

/** @type {import("tailwindcss").Config} */
const config = {
  darkMode: ["class"],
  content: [
    "./client/index.html",
    "./client/src/**/*.{ts,tsx}",
    "./shared/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: "var(--theme-radius-default, var(--radius))",
        xl: "var(--theme-radius-xl, calc(var(--radius) + 4px))",
        full: "var(--theme-radius-full, 9999px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        ...materialNamedColors,
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
          border: "hsl(var(--card-border) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
          border: "hsl(var(--popover-border) / <alpha-value>)",
        },
        primary: "var(--theme-color-primary, hsl(var(--primary) / <alpha-value>))",
        "primary-foreground": "var(--theme-color-on-primary, hsl(var(--primary-foreground) / <alpha-value>))",
        "primary-border": "var(--primary-border)",
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
          border: "var(--secondary-border)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
          border: "var(--muted-border)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
          border: "var(--accent-border)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
          border: "var(--destructive-border)",
        },
        chart: {
          "1": "hsl(var(--chart-1) / <alpha-value>)",
          "2": "hsl(var(--chart-2) / <alpha-value>)",
          "3": "hsl(var(--chart-3) / <alpha-value>)",
          "4": "hsl(var(--chart-4) / <alpha-value>)",
          "5": "hsl(var(--chart-5) / <alpha-value>)",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
          accent: "hsl(var(--accent) / <alpha-value>)",
          "accent-foreground": "hsl(var(--accent-foreground) / <alpha-value>)",
        },
      },
      fontFamily: {
        headline: "var(--theme-font-headline, var(--font-display))",
        body: "var(--theme-font-body, var(--font-sans))",
        label: "var(--theme-font-label, var(--font-sans))",
      },
      spacing: {
        "theme-xs": "var(--theme-space-xs, 0.5rem)",
        "theme-sm": "var(--theme-space-sm, 0.75rem)",
        "theme-md": "var(--theme-space-md, 1rem)",
        "theme-lg": "var(--theme-space-lg, 1.5rem)",
        "theme-xl": "var(--theme-space-xl, 2rem)",
        "theme-section-mobile": "var(--theme-space-section-mobile, 48px)",
        "theme-section-desktop": "var(--theme-space-section-desktop, 80px)",
      },
      maxWidth: {
        theme: "var(--theme-layout-max-width, 1120px)",
        "theme-content": "var(--theme-layout-content-width, 720px)",
      },
      gap: {
        theme: "var(--theme-layout-grid-gap, 24px)",
      },
      boxShadow: {
        "theme-raised": "var(--theme-shadow-raised, 0 2px 16px rgba(15, 23, 42, 0.12))",
        "theme-overlay": "var(--theme-shadow-overlay, 0 18px 52px rgba(15, 23, 42, 0.18))",
      },
      transitionDuration: {
        "theme-fast": "var(--theme-motion-duration-fast, 140ms)",
        "theme-normal": "var(--theme-motion-duration-normal, 220ms)",
        "theme-slow": "var(--theme-motion-duration-slow, 420ms)",
      },
      transitionTimingFunction: {
        "theme-standard": "var(--theme-motion-easing-standard, cubic-bezier(0.2, 0, 0, 1))",
        "theme-emphasized": "var(--theme-motion-easing-emphasized, cubic-bezier(0.16, 1, 0.3, 1))",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [animate],
};

export default config;
